# Generated by Django 2.2.3 on 2019-07-23 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='carpentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('imagedailyupdate', models.FileField(upload_to='')),
                ('latestcarpentryupdate', models.TextField()),
                ('user', models.CharField(max_length=40)),
                ('linktofurtherreading', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tailoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('imagedailyupdate', models.FileField(upload_to='')),
                ('latesttailoringupdate', models.TextField()),
                ('linktofurtherreading', models.TextField()),
                ('user', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(default='', max_length=100)),
                ('career_interests', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('image', models.FileField(upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofiled', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usernotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tailorcommenting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=40)),
                ('posting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commention', to='djapp.tailoring')),
            ],
        ),
        migrations.CreateModel(
            name='commenting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=40)),
                ('posting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commention', to='djapp.carpentry')),
            ],
        ),
    ]
